export enum Color {
  Black = 'black',
  Blue = 'blue',
  Brown = 'brown',
  Green = 'green',
  Pink = 'pink',
  Purple = 'purple',
  Red = 'red',
  White = 'white',
  Yellow = 'yellow',
}

export enum Appearance {
  PointyHair = 'pointyHair',
  ThreeHaired = 'threeHaired',
  TiedHair = 'tiedHair',
  WhiteHair = 'whiteHair',

  NoEars = 'noEars',
  Eared = 'eared',
  FloppyEars = 'floppyEars',
  PointyEars = 'pointyEars',
  RoundEars = 'roundEars',
  PinkEars = 'pinkEars',

  Eyebrows = 'eyebrows',
  Eyeslashes = 'eyeslashes',
  VisibleEyeWhites = 'visibleEyeWhites',

  BlackNose = 'blackNose',
  PinkNose = 'pinkNose',
  TriangleNose = 'triangleNose',

  Mouthed = 'mouthed',
  Beaked = 'beaked',
  RosyCheeks = 'rosyCheeks',
  FacialHair = 'facialHair',
  Horned = 'horned',

  BlackHands = 'blackHands',
  WhiteHands = 'whiteHands',
  YellowHands = 'yellowHands',
}

export enum Wear {
  WearRibbon = 'wearRibbon',
  WearCrown = 'wearCrown',
  WearHat = 'wearHat',
  WithCollar = 'withCollar',
  WithFollowers = 'withFollowers',
}

export enum Skill {
  Burst = 'burst',
  BurstBottom = 'burstBottom',
  BurstCenter = 'burstCenter',
  BurstDiagonal = 'burstDiagonal',
  BurstHorizontal = 'burstHorizontal',
  BurstRandom = 'burstRandom',
  BurstTypeOfTsum = 'burstTypeOfTsum',
  BurstVertical = 'burstVertical',
  OtherBursts = 'otherBursts',
  TapToBurst = 'tapToBurst',

  CallSomeone = 'callSomeone',
  CallFriend = 'callFriend',
  CallLover = 'callLover',
  CallMyTsum = 'callMyTsum',
  CallOthers = 'callOthers',

  MakeBatsAppear = 'makeBatsAppear',
  MakeBigTsum = 'makeBigTsum',
  MakeHearts = 'makeHearts',

  MakeMagicalBubbles = 'makeMagicalBubbles',
  MakeItemBubbles = 'makeItemBubbles',
  MakeScoreBubbles = 'makeScoreBubbles',
  MakeTimeBubbles = 'makeTimeBubbles',

  MakePumpkinsAppear = 'makePumpkinsAppear',
  StartFeverTime = 'startFeverTime',
  StopTime = 'stopTime',
  TailSwishing = 'tailSwishing',
}

export enum Gender {
  Female = 'female',
  Male = 'male',
  Unknown = 'unknown',
}

export enum Box {
  Happiness = 'happiness',
  Premium = 'premium',
}

export enum Other {
  Dog = 'dog',
  Cat = 'cat',
  Rabbit = 'rabbit',
  Halloween = 'halloween',
  Holiday = 'holiday',
  Marine = 'marine',
  Prince = 'prince',
  Princess = 'princess',
  Villain = 'villain',
  Pixar = 'pixar',
  ThreeEyedAlien = 'threeEyedAlien',
}

export enum MickeyAndFriends {
  Mickey = 'mickey',
  Minnie = 'minnie',
  Donald = 'donald',
  Goofy = 'goofy',
  MickeyAndFriends = 'mickeyAndFriends',
}

export enum Initial {
  A = 'initialA',
  B = 'initialB',
  D = 'initialD',
  J = 'initialJ',
  M = 'initialM',
  N = 'initialN',
  P = 'initialP',
  S = 'initialS',
  T = 'initialT',
}

export enum Series {
  OneHundredAndOneDalmatians = '101Dalmatians',
  ABugsLife = 'aBugsLife',
  ATsumTsumShort = 'aTsumTsumShort',
  Aladdin = 'aladdin',
  AliceInWonderland = 'aliceInWonderland',
  Bambi = 'bambi',
  BeautyAndTheBeast = 'beautyAndTheBeast',
  BigHero6 = 'bigHero6',
  Brave = 'brave',
  Cars = 'cars',
  ChipAndDale = 'chipAndDale',
  ChipAndDaleRescueArangers = 'chipAndDaleRescueArangers',
  Cinderella = 'cinderella',
  Coco = 'coco',
  CountryBearJamboree = 'countryBearJamboree',
  DisneyFairies = 'disneyFairies',
  Dumbo = 'dumbo',
  Enchanted = 'enchanted',
  Fantasia = 'fantasia',
  FindingNemo = 'findingNemo',
  Frozen = 'frozen',
  Hercules = 'hercules',
  InsideOut = 'insideOut',
  JungleBook = 'jungleBook',
  KingdomHearts = 'kingdomHearts',
  LadyAndTheTramp = 'ladyAndTheTramp',
  LiloAndStitch = 'liloAndStitch',
  LittleMermaid = 'littleMermaid',
  Maleficent = 'maleficent',
  MaryPoppins = 'maryPoppins',
  MickeyAndFriends = 'mickeyAndFriends',
  Moana = 'moana',
  MonstersInc = 'monstersInc',
  Mulan = 'mulan',
  Onward = 'onward',
  OswaldTheLuckyRabbit = 'oswaldTheLuckyRabbit',
  PetesDragon = 'petesDragon',
  PeterPan = 'peterPan',
  PhineasAndFerb = 'phineasAndFerb',
  Pinocchio = 'pinocchio',
  PiratesOfTheCaribbea = 'piratesOfTheCaribbea',
  Pocahontas = 'pocahontas',
  Ratatouille = 'ratatouille',
  RobinHood = 'robinHood',
  SleepingBeauty = 'sleepingBeauty',
  SnowWhite = 'snowWhite',
  SofiaTheFirst = 'sofiaTheFirst',
  StarWars = 'starWars',
  SteamboatWillie = 'steamboatWillie',
  Tangled = 'tangled',
  TheAristocats = 'theAristocats',
  TheBlackCauldron = 'theBlackCauldron',
  TheGoodDinosaur = 'theGoodDinosaur',
  TheHauntedMansion = 'theHauntedMansion',
  TheHunchbackOfNotreDame = 'theHunchbackOfNotreDame',
  TheIncredibles = 'theIncredibles',
  TheLionKing = 'theLionKing',
  TheNightmareBeforeChristmas = 'theNightmareBeforeChristmas',
  ThePrincessAndTheFrog = 'thePrincessAndTheFrog',
  TheRescuers = 'theRescuers',
  TheSwordInTheStone = 'theSwordInTheStone',
  TheThreeCaballeros = 'theThreeCaballeros',
  TheThreeMusketeers = 'theThreeMusketeers',
  ThreeLittlePigs = 'threeLittlePigs',
  ToyStory = 'toyStory',
  Up = 'up',
  WallE = 'wallE',
  WinnieThePooh = 'winnieThePooh',
  WreckItRalph = 'wreckItRalph',
  Zootopia = 'zootopia',
}
